camera_name: "front_camera"
frame_id: "$(var rc)/front_camera"
video_stream_provider: "/dev/video_front"
width: 640
height: 480
set_camera_fps: 30
fps: 30
camera_info_url: "file://$(env HOME)/.ros/camera_info/front_camera.yaml"
buffer_queue_size: 3
