global_costmap:
    footprint: [[-0.08, -0.09], [0.34, -0.09], [0.34, 0.09], [-0.08, 0.09]]
    update_frequency: 0.5
    publish_frequency: 0.5
    global_frame: map
    robot_base_frame: $(env RC110_NAME)/base_link
    width: 20
    height: 20
    resolution: 0.1
    origin_x: -10
    origin_y: -10

    plugins:
        - {name: static_map, type: "costmap_2d::StaticLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}