#!/bin/bash

# Copy config files from installation directory to editable directory, if they have not existed already.

config_prefix="@RC110_SHARE_PATH@"
default_config=${config_prefix}/config_default
editable_config=${config_prefix}/config

mkdir -p ${editable_config}

for default_file in ${default_config}/*.yaml
do
    editable_file=${editable_config}/$(basename ${default_file})
    if [ ! -f ${editable_file} ]; then
        cp ${default_file} ${editable_file}
    fi
done
