#!/bin/bash

script_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
mkdir -p /etc/ros/rosdep/sources.list.d

cp -f "${script_dir}/20-default.list" /etc/ros/rosdep/sources.list.d/
cp -rf "${script_dir}/config" /etc/ros/rosdep/
