#!/bin/bash -e

sudo dpkg --configure -a  # resolves "Internal Error, No file name for"
sudo apt-get install -qq --allow-downgrades --reinstall ./*.deb
sudo apt-mark auto ros-rolling-rc110-'*'  # single quoted, to avoid file expansion
sudo apt-mark manual ros-rolling-rc110-system
sudo apt-mark manual ros-rolling-rc110-rviz
sudo apt-get autoremove -yq

sudo systemctl --global disable rc110 2>/dev/null  # fix multiple starts from different users (was part of package before)

loginctl enable-linger          # user login is not required for services to start (should be run from one user)
systemctl --user enable /opt/ros/rolling/systemd/rc110.service
systemctl --user daemon-reload  # automatic files reload - it does not work from postinst, as root runs postinst
