set(CPACK_GENERATOR DEB CACHE STRING "")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT CACHE STRING "")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ZMP Inc. <info@zmp.co.jp>" CACHE STRING "")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${CMAKE_PROJECT_NAME}" CACHE STRING "")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}" CACHE STRING "")
set(CPACK_DEBIAN_PACKAGE_RELEASE "" CACHE STRING "")
set(CPACK_PACKAGING_INSTALL_PREFIX /opt/ros/$ENV{ROS_DISTRO} CACHE STRING "")

include(CPack)